### ISSUE TITLE
FormGenerator Ошибка

### ISSUE THREAD

**Issue by Alauda89** [ChanTerelLy/FormGenerator#3]
Привет, не могу ни один протокол теперь залить
перебил в .xls
потом опять в .xlsx
пишет неверный формат
![111](https://user-images.githubusercontent.com/50729376/65475637-3458db80-debb-11e9-910e-267f81e88af9.jpg)

**Comment by ChanTerelLy** [comment]
https://github.com/ChanTerelLy/FormGenerator/tree/fix_product_version
